### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by fbclh** [david-lafontant/Portfolio#19]
- Page seems foundational, however I would try to follow and sticky with the original design as much as possible. (It is a good practice as a front-end because in the job you are required to clone exactly as it is).
- In my view I would not nest many section tags, I would use one main section when need and then if needed use divs a container/wrapper (But it is totally up to you).

**Comment by gabyse1** [comment]
## Nice design David
I think **:nth-child()** CSS pseudo-class could help you to give different styles to the odd and even card positions in an easy way. This way you will not require adding position-a and position-b classes in the markup.
