### ISSUE TITLE
Peer to Peer code reviews

### ISSUE THREAD

**Issue by hendridg** [david-lafontant/Portfolio#23]
# Peer to Peer code reviews

## Learning objectives

- Understand the code review process as a team effort.
- Understand the Microverse program code review flow.
- Write clear and professional code review comments.

**Comment by hendridg** [comment]
# Excellent Excellent Excellent

You make it a beatiful jobs :fire: :fire: 

![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)

Very nice @david-lafontant, I just recommended moving a little bit the `error message` near the bottom

**Comment by david-lafontant** [comment]
Thank you guys for your help and advice.
![ ](https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif)
